# Generated by Django 5.0.1 on 2024-01-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
    ]
