# Generated by Django 5.0.1 on 2024-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_post", "0001_initial"),
        ("main_user", "0002_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_liked",
            field=models.ManyToManyField(related_name="liked_by", to="main_post.post"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
